# cpputest-turbo — C11 core + thin C++ shim, GNU make + gcc/clang only.

CC       ?= gcc
CXX      ?= g++
AR       ?= ar

BUILD    := build
INCLUDES := -Iinclude

# CFLAGS/CXXFLAGS belong to the user (make CFLAGS=-O0 must not break the
# build); the flags the build REQUIRES are kept separate and always applied.
CFLAGS       ?= -O2 -g
CXXFLAGS     ?= -O2 -g

# warnings beyond the always-on set, accepted only if this compiler knows
# them (gcc-only diagnostics must not break the clang CI legs)
try-cflag   = $(if $(shell $(CC) -Werror $(1) -std=c11 -x c -c /dev/null -o /dev/null 2>/dev/null && echo y),$(1))
try-cxxflag = $(if $(shell $(CXX) -Werror $(1) -std=c++11 -x c++ -c /dev/null -o /dev/null 2>/dev/null && echo y),$(1))
EXTRA_WARN_C   := $(foreach f,-Wlogical-op -Wduplicated-cond -Wduplicated-branches \
                              -Wjump-misses-init,$(call try-cflag,$(f)))
EXTRA_WARN_CXX := $(foreach f,-Wuseless-cast -Wzero-as-null-pointer-constant,$(call try-cxxflag,$(f)))

REQ_CFLAGS   := -std=c11 -Wall -Wextra -Werror -Wpedantic -Wshadow \
                -Wstrict-prototypes -Wmissing-prototypes -Wundef \
                -Wwrite-strings -Wconversion -Wsign-conversion \
                -Wpointer-arith -Wvla -Wformat=2 -Wcast-align \
                -Wnull-dereference -Wdouble-promotion \
                $(EXTRA_WARN_C) $(INCLUDES)
REQ_CXXFLAGS := -std=c++11 -Wall -Wextra -Werror -Wpedantic -Wshadow \
                -Wundef -Wconversion -Wsign-conversion \
                -Wpointer-arith -Wvla -Wformat=2 -Wcast-align \
                -Wnon-virtual-dtor -Wdouble-promotion \
                $(EXTRA_WARN_CXX) $(INCLUDES)

PREFIX   ?= /usr/local
DESTDIR  ?=

CORE_SRC := $(wildcard src/core/*.c)
CORE_OBJ := $(CORE_SRC:src/core/%.c=$(BUILD)/core/%.o)
LIB      := $(BUILD)/libCppUTest.a

# The C++ TUs: global operator new/delete replacements for leak tracking and
# the out-of-line SimpleString. C-only consumers: `make CPPUTEST_C_ONLY=1`
# skips them (the C core and TestHarness_c work fully without them).
ifndef CPPUTEST_C_ONLY
SHIM_SRC := $(wildcard src/shim/*.cpp)
SHIM_OBJ := $(SHIM_SRC:src/shim/%.cpp=$(BUILD)/shim/%.o)
endif

MOCK_SRC := $(wildcard src/mock/*.c)
MOCK_OBJ := $(MOCK_SRC:src/mock/%.c=$(BUILD)/mock/%.o)
EXT_LIB  := $(BUILD)/libCppUTestExt.a

ALL_OBJ  := $(CORE_OBJ) $(MOCK_OBJ) $(SHIM_OBJ)

.PHONY: all check lint clean install uninstall

all: $(LIB) $(if $(MOCK_SRC),$(EXT_LIB))

$(BUILD)/core/%.o: src/core/%.c
	@mkdir -p $(dir $@)
	$(CC) $(REQ_CFLAGS) $(CFLAGS) -MMD -MP -c $< -o $@

$(BUILD)/mock/%.o: src/mock/%.c
	@mkdir -p $(dir $@)
	$(CC) $(REQ_CFLAGS) $(CFLAGS) -MMD -MP -c $< -o $@

$(BUILD)/shim/%.o: src/shim/%.cpp
	@mkdir -p $(dir $@)
	$(CXX) $(REQ_CXXFLAGS) $(CXXFLAGS) -MMD -MP -c $< -o $@

# header dependencies generated by -MMD: editing internal.h or a public
# header rebuilds exactly the objects that include it
-include $(ALL_OBJ:.o=.d)

# remove before archiving: `ar rcs` updates in place, so a renamed/deleted
# source would otherwise leave its stale object inside the archive
$(LIB): $(CORE_OBJ) $(SHIM_OBJ)
	rm -f $@
	$(AR) rcs $@ $^

$(EXT_LIB): $(MOCK_OBJ)
	rm -f $@
	$(AR) rcs $@ $^

check: all
	@./scripts/run-unit-tests.sh

lint:
	@./scripts/check-analyzer.sh

install: all
	mkdir -p $(DESTDIR)$(PREFIX)/lib $(DESTDIR)$(PREFIX)/include \
	         $(DESTDIR)$(PREFIX)/lib/pkgconfig
	cp $(LIB) $(EXT_LIB) $(DESTDIR)$(PREFIX)/lib/
	cp -R include/CppUTest include/CppUTestExt include/cpputest_core \
	      $(DESTDIR)$(PREFIX)/include/
	sed 's|@PREFIX@|$(PREFIX)|' cpputest.pc.in \
	    > $(DESTDIR)$(PREFIX)/lib/pkgconfig/cpputest.pc

uninstall:
	rm -f $(DESTDIR)$(PREFIX)/lib/libCppUTest.a \
	      $(DESTDIR)$(PREFIX)/lib/libCppUTestExt.a \
	      $(DESTDIR)$(PREFIX)/lib/pkgconfig/cpputest.pc
	rm -rf $(DESTDIR)$(PREFIX)/include/CppUTest \
	       $(DESTDIR)$(PREFIX)/include/CppUTestExt \
	       $(DESTDIR)$(PREFIX)/include/cpputest_core

clean:
	rm -rf $(BUILD)
